apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage-frontend
  labels:
    app: frontend
    env: dev
spec:
  selector:
    matchLabels:
      app: frontend
      env: dev
  replicas: 1
  template:
    metadata:
      name: storage-frontend
      labels:
        app: frontend
        env: dev
    spec:
      restartPolicy: Always
      containers:
      - name: storage-frontend
        image: daocloud.io/alaien/storage-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command: ["java","-jar","-Dspring.profiles.active=dev","-Dcustom.backendUrl=storage-backend","storage-frontend.jar"]

---

apiVersion: v1
kind: Service
metadata:
  name: storage-frontend
  labels:
    app: frontend
    env: dev
spec:
  selector:
    app: frontend
    env: dev
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30000
    targetPort: 8000